# Refer to gitlab CI job configuration docs for details
# https://docs.gitlab.com/ee/ci/yaml/
image: docker-registry.int.aisingapore.org/gitlab-runner-vishnu:latest

variables:
  VISHNU_IMG: "vishnu:test"

stages:
  - code_check
  - tests
  - deploy

code_check:
  stage: code_check
  script:
    - pip install -r requirements.txt
    - pylint -E vishnu
    - cd frontend && npm install && npm run build && cd ..
    - docker build . -t $VISHNU_IMG # Check to ensure docker image for app can be built
    - helm lint ci/vishnu

tests:
  stage: tests
  script:
    - echo "Running npm tests"
    - cd frontend && npm install
    - npm run lint
#    - npm run test

deploy:
  stage: deploy
  when: manual
  only:
    refs:
      - master
  script:
    - sed -i "s/RELEASE_NAME/$RELEASE_NAME/g" skaffold.yaml
    - cd frontend && npm install && npm run build && cd ..
    - docker login -u $ACR_USERNAME -p $ACR_KEY 100edockerregistry.azurecr.io
    - echo "$KUBE_CONFIG $KUBE_NS $KUBE_CTX"
    - helm version
    - skaffold run --namespace=$KUBE_NS --kubeconfig=$KUBE_CONFIG --kube-context=$KUBE_CTX --status-check=false