# Refer to gitlab CI job configuration docs for details
# https://docs.gitlab.com/ee/ci/yaml/
image: docker-registry.int.aisingapore.org/gitlab-runner-sensemaker:latest

variables:
  vishnu_IMG: "vishnu:test"

stages:
  - code_check
  - tests
  - deploy

code_check:
  stage: code_check
  script:
    - pip install -r requirements.txt
    - pylint -E vishnu
    - cd frontend && npm install && npm run build && cd ..
    - docker build . -t $vishnu_IMG # Check to ensure docker image for app can be built
    - helm lint ci/vishnu

tests:
  stage: tests
  script:
    - echo "Running npm tests"
    - cd frontend && npm install
    - npm run lint
    - npm run test

deploy:
  stage: deploy
  only:
    refs:
      - deploy
  script:
    - cd frontend && npm install && npm run build && cd ..
    - docker login -u $ACR_USERNAME -p $ACR_KEY 100edockerregistry.azurecr.io
    - skaffold run