version: '3'
services:
  
  postgres_vishnu:
    image: "postgres:12.0"
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data