apiVersion: skaffold/v1
kind: Config
metadata:
  name: vishnu
build:
  artifacts:
  - image: 100edockerregistry.azurecr.io/vishnu
#  local:
#    push: false
deploy:
  helm:
    flags:
      upgrade:
        - --install
    releases:
      - name: RELEASE_NAME
        chartPath: ci/vishnu
        values:
          image: 100edockerregistry.azurecr.io/vishnu
        setValueTemplates:
          postgresql.password: "{{.POSTGRES_PASSWORD}}"
          ingress.hosts[0]: "{{.INGRESS_HOST}}"
