apiVersion: v1
kind: Secret
metadata:
  name: vishnu-postgresql
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.password | b64enc }}
  postgresql-postgres-password: {{ .Values.postgresql.password | b64enc }}