#kind: StorageClass
#apiVersion: storage.k8s.io/v1
#metadata:
#  name: aks-managed-retain
#provisioner: kubernetes.io/azure-disk
#reclaimPolicy: Retain
#parameters:
#  storageaccounttype: Standard_LRS
#  kind: Managed
#---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile-prem
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=1000
  - gid=1000
parameters:
  skuName: Premium_LRS
allowVolumeExpansion: true