# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - loa.ai3.aisingapore.org
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

  tls:
    - secretName: loa-tls-secret
      hosts:
        - "loa.ai3.aisingapore.org"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

postgresql:
  image:
    tag: 12.0
  persistence:
    existingClaim: "vishnu-pvc-postgresql"
  postgresqlUsername: "vishnu"
  postgresqlDatabase: "vishnudb"
  existingSecret: "vishnu-postgresql"
  # below is not the real password, real password needs to be passed in when running Helm
#  postgresqlPostgresPassword: password