apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "vishnu.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vishnu.name" . }}
    helm.sh/chart: {{ include "vishnu.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vishnu.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vishnu.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: vishnu-volume
          persistentVolumeClaim:
            claimName: {{ include "vishnu.pvc" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: "POSTGRES_USER"
              value: {{ include "vishnu.postgres.username" . }}
            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "vishnu-postgresql"
                  key: "postgresql-password"
            - name: "POSTGRES_DB"
              value: "vishnudb"
            - name: "POSTGRES_HOST"
              value: {{ include "vishnu.postgres.host" . }}
          envFrom:
            - configMapRef:
                name: prod-configmap
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: {{ .Values.volumes.mount.uploads }}
              name: vishnu-volume
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
