kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "vishnu.pvc" . }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "azurefile-prem"
  resources:
    requests:
      storage: 100Gi